name: icd
description: A flutter package that allows programmatic access to the International Classification of Diseases (ICD) API.
version: 0.0.5
homepage: https://github.com/Princewil/icd

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
